OPTIMIZATION_FIGURE_PATH = "output/figure"
SECOND_OPTIMIZATION_FIGURE_PATH = "output/figure_second"
MODEL_PATH = "output/data_model"
ENERGY_PATH = "output/energy"
SVD_MODEL_PATH = "output/svd_model"
DATE_PATH = "input/dates.txt"
PRICE_PATH = "input/prices.txt"
ENTROPY_PATH = "output/entropy"
COEFFICIENT_PATH = "output/coefficients"
ENERGY_KEY = "final-energy"
LAYER_KEY = "layer"
DEFAULT_PREFIX = "default"
CLASSICAL_PREFIX = "classical"
NAIVE_PREFIX = "naive"
DEFAULT_ENTROPY_PREFIXES = [DEFAULT_PREFIX, NAIVE_PREFIX, CLASSICAL_PREFIX]
DEFAULT_STOCKS = ["XOM", "WMT", "PG", "MSFT"]
DATA_QUBITS = 5
SVD_QUBITS = 4
SVD_LOCAL_QUBITS = 2
INTEGER_MAX = 100000000
TIME_SPAN = 5
STOCK_COUNT = 4
